### ISSUE TITLE
INTERBVAL Cast to TIMESTAMP WITH TIMEZONE missing

### ISSUE THREAD

**Issue by prmah** [paradedb/pg_analytics#181] opened 2024-11-26 10:23 UTC
### What happens?

between quries like "arrival-time between now() - interval '30 days' and now() - interval '7 days'" are failing with below error

Binder Error: No function matches the given name and argument types '-(TIMESTAMP WITH TIME ZONE, INTERVAL)'. You might need to add explicit type casts.
	Candidate functions:
	-(TINYINT) -> TINYINT
	-(TINYINT, TINYINT) -> TINYINT
	-(SMALLINT) -> SMALLINT
	-(SMALLINT, SMALLINT) -> SMALLINT
	-(INTEGER) -> INTEGER
	-(INTEGER, INTEGER) -> INTEGER
	-(BIGINT) -> BIGINT
	-(BIGINT, BIGINT) -> BIGINT
	-(HUGEINT) -> HUGEINT
	-(HUGEINT, HUGEINT) -> HUGEINT
	-(FLOAT) -> FLOAT
	-(FLOAT, FLOAT) -> FLOAT
	-(DOUBLE) -> DOUBLE
	-(DOUBLE, DOUBLE) -> DOUBLE
	-(DECIMAL) -> DECIMAL
	-(DECIMAL, DECIMAL) -> DECIMAL
	-(UTINYINT) -> UTINYINT
	-(UTINYINT, UTINYINT) -> UTINYINT
	-(USMALLINT) -> USMALLINT
	-(USMALLINT, USMALLINT) -> USMALLINT
	-(UINTEGER) -> UINTEGER
	-(UINTEGER, UINTEGER) -> UINTEGER
	-(UBIGINT) -> UBIGINT
	-(UBIGINT, UBIGINT) -> UBIGINT
	-(UHUGEINT) -> UHUGEINT
	-(UHUGEINT, UHUGEINT) -> UHUGEINT
	-(DATE, DATE) -> BIGINT
	-(DATE, INTEGER) -> DATE
	-(TIMESTAMP, TIMESTAMP) -> INTERVAL
	-(INTERVAL, INTERVAL) -> INTERVAL
	-(DATE, INTERVAL) -> TIMESTAMP
	-(TIME, INTERVAL) -> TIME
	-(TIMESTAMP, INTERVAL) -> TIMESTAMP
	-(TIME WITH TIME ZONE, INTERVAL) -> TIME WITH TIME ZONE
	-(INTERVAL) -> INTERVAL

### To Reproduce

try a between quries like "arrival-time between now() - interval '30 days' and now() - interval '7 days'" 

### OS:

x64

### ParadeDB Version:

0.13.0-pg13

### Are you using ParadeDB Docker, Helm, or the extension(s) standalone?

ParadeDB Docker Image

### Full Name:

Preshit Maheshwari

### Affiliation:

-

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by philippemnoel** [comment] 2024-11-26 15:46
This is a duplicate of #48, closing.

**Closed by philippemnoel** 2024-11-26 15:46 UTC
Labels: bug
